name: 'Puppet Development Kit Tests'
description: 'Run PDK commands in GitHub Actions'
author: 'okopop'
inputs:
  action:
    description: 'PDK commands'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
